# Generated by Django 2.2.1 on 2019-05-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='note',
            new_name='notes',
        ),
    ]
